### ISSUE TITLE
Welcome to Marketing School!

### ISSUE THREAD

**Issue by Indexerrowaty** [05xapresses/spe-sopot-pl-dark-theme#1]
The only podcast that provides daily top level tips and strategies from entreprenours that practice what they preach and live what they teach. Let's start leveling up your marketing knowledge with your instructors Neil Patel and Eric Siu.

> St. Eric Siu
> A real gamer that took the concept of gaming and applied it to real life.
>
> ![eric-siu-singlegrain-kopia](https://user-images.githubusercontent.com/39349444/114921417-d5571080-9e2a-11eb-811f-7484a13ca56a.png)

**Comment by 05xapresses** [comment]
am I a real gamer?

**Comment by Indexerrowaty** [comment]
> am I a real gamer?

Only St. Eric Siu can tell.

**Comment by 05xapresses** [comment]
Oh okay, I'll contact him later
